apiVersion: v1
clusters:
- cluster:
    server: https://98.81.157.252:6443
    insecure-skip-tls-verify: true
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJT0dOUE5oblpZY1V3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemMxTnpZME1EazJNQjRYRFRJMk1EUXdPVEU0TkRneE5sb1hEVEkzTURRdwpPVEU0TkRneE5sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJOb1NmTGdGOEJIYlVvaUQKdlBUejk0YitHMDRieG0wR1gwR3hKRk9QdHBPOUtneTF0b1NoTUVTdFYrSHloazA5WTJCTEFuckswTEJhUUs5TwppdEtxM0wyalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUkhoU1YwajlnWmZIYmR2aXh2c0hXd3N0bkxsREFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlCWFF3MnNOR3VONHhqZDZQSG8vS1BCWXZJZk1KNWRRTkhUZXBhUjlhZmMyd0loQUpIRzhBdXgwS0NrbkN3Rwp3aUl1WEtBRkZTVE1uZndYaTZZc0lQL0NlSjIxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTnpVM05qUXdPVFl3SGhjTk1qWXdOREE1TVRnME9ERTJXaGNOTXpZd05EQTJNVGcwT0RFMgpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTnpVM05qUXdPVFl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUSFlUZ3BIUTB0SmNTSTRTdWdpdk1MRzJHK29iWEh2cDhmWFdNQTVpT0EKKzV1cEwvNzFhQnVKRlJKUjlGZllveEdsRTZsb0hoNmpwUFp3eDFZYmxTSjhvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVI0VWxkSS9ZR1h4MjNiNHNiN0IxCnNMTFp5NVF3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnYXNKelFxUnovTzBsd0tVNU5uTGY3dS9QTzFKaTBESTIKcE81eFJkSThJNG9DSURvdTRmOFF6YjR5bVZnYjUvb2RucmJOS015RUlnKzA0NlFINE5vOUxJN3MKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUd0aGRkTkx2TytjbFRlUDBhZ3NzdkpqNWZqb3Jrb09xZEkvN2J1WVBHTVlvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFMmhKOHVBWHdFZHRTaUlPODlQUDNodjRiVGh2R2JRWmZRYkVrVTQrMms3MHFETFcyaEtFdwpSSzFYNGZLR1RUMWpZRXNDZXNyUXNGcEFyMDZLMHFyY3ZRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
