apiVersion: apps/v1
kind: Deployment
metadata:
  name: iss-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iss-backend
  template:
    metadata:
      labels:
        app: iss-backend
    spec:
      containers:
      - name: backend
        image: 22i0838/iss-backend:d3f5978ffffb17c4f2e58e3561579e783461090c
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: iss-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000